### ISSUE TITLE
[SUGGESTION] Close when Inventory key is pressed.

### ISSUE THREAD

**Issue by DevBefell** [Dance-Dog/RewardClaim#1]
This mod is amazing, just wondering if you can close when the inventory key (deafult E) is pressed instead of always pressing the ESCAPE key.

**Comment by Dance-Dog** [comment]
Are you asking for all GUIs to be closed or for the GUI to be switched over to the inventory?

**Comment by DevBefell** [comment]
to be closed, with the inventory key.

**Comment by DevBefell** [comment]
and is it possible to add the daily Streak that shows on the website?

**Comment by Dance-Dog** [comment]
Sounds good! I can sneak the inventory-to-close feature into the next update, but streak info will have to come after I implement ads of some form (my top priority rn). It's definitely possible and on the todo list, it'll just have to come after that.

**Comment by DevBefell** [comment]
thank you so much!  I am looking forward to the update!
